# ============================================================================
# proguard-rules.pro - Plantilla_ajedrez
# ----------------------------------------------------------------------------
# Reglas R8/ProGuard para release a Play Console.
# Objetivo: reducir tamaño y ofuscar, SIN romper:
#   - Hilt (generación + anotaciones + reflexión)
#   - Room (entidades, DAOs, autogenerated code)
#   - chesslib (constantes, enums, reflexión de PgnHolder)
#   - JNI Stockfish (símbolos nativos)
#   - Anotaciones @Keep clave
# ============================================================================

# --- @Keep: nunca se ofusca lo marcado --------------------------------------
-keep,allowobfuscation @interface androidx.annotation.Keep
-keep @androidx.annotation.Keep class * { *; }

# --- Hilt / Dagger ----------------------------------------------------------
# Hilt genera y accede por reflexión a clases inyectadas. Mantener entradas.
-keep class dagger.hilt.** { *; }
-keep class * extends dagger.hilt.android.HiltAndroidApp { *; }
-keep,allowobfuscation @dagger.hilt.android.HiltAndroidApp class *
-keep,allowobfuscation @dagger.hilt.android.lifecycle.HiltViewModel class * { <init>(...); }
-keep,allowobfuscation @javax.inject.Inject class *
-keep,allowobfuscation @javax.inject.Qualifier @interface *
-keep,allowobfuscation @javax.inject.Scope @interface *
-keep class * extends androidx.lifecycle.ViewModel { <init>(...); }

# --- Room -------------------------------------------------------------------
# Room genera código a partir de entidades y DAOs; hay que preservarlos.
-keep class * extends androidx.room.RoomDatabase { *; }
-keep @androidx.room.Entity class * { *; }
-keep @androidx.room.Dao class * { *; }
-keep class androidx.room.** { *; }
-dontwarn androidx.room.paging.**

# Mantener nombres de columnas/tablas (Room usa reflexión en runtime).
-keepclassmembers class * {
    @androidx.room.ColumnInfo <fields>;
}

# --- chesslib (Apache 2.0) --------------------------------------------------
# Usa enums (Square, Piece, Side, Move) y reflexión en PgnHolder/Game.
-keep class com.github.bhukk.chesslib.** { *; }
-keep class chesslib.** { *; }
-keep class com.github.buklangonijr.chesslib.** { *; }
# Forma canónica del paquete:
-keep class com.github.bhlangonijr.chesslib.** { *; }
-keep enum com.github.bhlangonijr.chesslib.** { *; }
-dontwarn com.github.bhlangonijr.chesslib.**

# --- JNI: Stockfish ---------------------------------------------------------
# La librería nativa se carga con System.loadLibrary("stockfish"); al proceso
# se le pasa FEN. Aseguramos los símbolos nativos disponibles.
-keepclasseswithmembernames class * {
    native <methods>;
}

# --- Corutinas y kotlinx ---------------------------------------------------
-keepclassmembers class kotlinx.coroutines.** {
    volatile <fields>;
}
-dontwarn kotlinx.coroutines.**

# --- Anotaciones JSR305 (usadas por domain para null-safety). ---------------
-keep,allowobfuscation @javax.annotation.Nonnull class *
-keep,allowobfuscation @javax.annotation.Nullable class *
-dontwarn javax.annotation.**

# --- Compose / Material 3 / Navigation -------------------------------------
# Normalmente no necesitan keeps manuales (sus consumer-rules los traen),
# pero garantizamos las hash-keys de Compose en runtime.
-keepclassmembers class androidx.compose.runtime.** { *; }
-dontwarn androidx.compose.**

# --- Seguridad / integridad: nunca loggear datos sensibles en release ------
-assumenosideeffects class android.util.Log {
    public static *** v(...);
    public static *** d(...);
    public static *** i(...);
}